version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vladrusinov/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/cats/images

  frontend:
    env_file: .env
    image: vladrusinov/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: vladrusinov/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/cats/images
